### ISSUE TITLE
Detecting USB connected

### ISSUE THREAD

**Issue by MPC-BlackBox** [ataradov/vcp#1]
Hi Alex,

I have been testing the VCP code and its working great.

I want to send out a welcome screen on the USB connection but I cannot see how to detect that the USB connection has been before sending any data.

Are there any flags I can check to determine the USB connection has completed and can be used?

Many Thanks,

MPC

**Comment by ataradov** [comment]
usb_configuration_callback() is called after device is connected and all the endpoints are initialized. But that's probably too early for the CDC to receive the data.

I'm not 100% sure, so you will have to experiment, but  usb_cdc_line_coding_updated() and usb_cdc_control_line_state_update() are called around the time port is open. So they may be a good place.

It will probably be a good idea to integrate this sending into the reset of the flow by putting the data in the app_send_buffer. Things get trickier if the size of the message is bigger than the endpoint size.
