### ISSUE TITLE
feature request: USB vendor request for mode switch to bootloader.

### ISSUE THREAD

**Issue by kimstik** [ataradov/vcp#3]
As reference I may point [usb-modeswitch](https://github.com/Danw33/usb-modeswitch) project.

**Comment by ataradov** [comment]
The goal of this project is not to provide an all-in-one universal solution, but to provide a basic example code. If someone needs this functionality they are free to implement it however they want.

**Comment by kimstik** [comment]
Thanks! Boot switch is nothing to do with all-in-one universality.
Lets continue with reset button.
