### ISSUE TITLE
feature request: software mode (putchar/getchar)

### ISSUE THREAD

**Issue by kimstik** [ataradov/vcp#4]
In this (simplified) configuration CDC communication may expose only 2 functions: putchar/getchar.
It may be useful for application which require only USB communication but not real UART side.

Test app may be simple thermometer which send internal temperature every second.

**Comment by ataradov** [comment]
Same idea. I'm not making universal frameworks. If someone needs a simpler API - they are free to implement it.

**Comment by kimstik** [comment]
Good to know. Thanks.
